"""ingestion control

Revision ID: 0010_ingestion_control
Revises: 0009_ai_details
Create Date: 2026-10-05 11:50:02.031725+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0010_ingestion_control"
down_revision: str | None = "0009_ai_details"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingestion_runs",
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("scope", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_requested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sources_total", sa.Integer(), nullable=False),
        sa.Column("sources_completed", sa.Integer(), nullable=False),
        sa.Column("sources_succeeded", sa.Integer(), nullable=False),
        sa.Column("sources_partial", sa.Integer(), nullable=False),
        sa.Column("sources_failed", sa.Integer(), nullable=False),
        sa.Column("jobs_discovered", sa.Integer(), nullable=False),
        sa.Column("jobs_accepted", sa.Integer(), nullable=False),
        sa.Column("jobs_rejected", sa.Integer(), nullable=False),
        sa.Column("jobs_created", sa.Integer(), nullable=False),
        sa.Column("jobs_updated", sa.Integer(), nullable=False),
        sa.Column("jobs_unchanged", sa.Integer(), nullable=False),
        sa.Column("jobs_closed", sa.Integer(), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_ingestion_run_created", "ingestion_runs", ["created_at"], unique=False
    )
    op.create_index(
        "uq_ingestion_active_run",
        "ingestion_runs",
        [sa.literal_column("(true)")],
        unique=True,
        postgresql_where=sa.text("status IN ('PENDING','RUNNING')"),
    )
    op.create_table(
        "ingestion_policies",
        sa.Column("source_id", sa.UUID(), nullable=True),
        sa.Column(
            "allowed_country_codes",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("include_unknown_country", sa.Boolean(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id"),
    )
    op.create_index(
        "uq_ingestion_global_policy",
        "ingestion_policies",
        [sa.literal_column("(true)")],
        unique=True,
        postgresql_where=sa.text("source_id IS NULL"),
    )
    op.create_table(
        "ingestion_source_runs",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("source_name", sa.Text(), nullable=False),
        sa.Column("ats_type", sa.String(length=50), nullable=False),
        sa.Column(
            "source_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "policy_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Float(), nullable=False),
        sa.Column("acquisition_complete", sa.Boolean(), nullable=False),
        sa.Column("closure_authorized", sa.Boolean(), nullable=False),
        sa.Column("closure_suppression_reason", sa.Text(), nullable=True),
        sa.Column("warnings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("warning_count", sa.Integer(), nullable=False),
        sa.Column("error_type", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("jobs_discovered", sa.Integer(), nullable=False),
        sa.Column("jobs_accepted", sa.Integer(), nullable=False),
        sa.Column("jobs_rejected", sa.Integer(), nullable=False),
        sa.Column("jobs_created", sa.Integer(), nullable=False),
        sa.Column("jobs_updated", sa.Integer(), nullable=False),
        sa.Column("jobs_unchanged", sa.Integer(), nullable=False),
        sa.Column("jobs_closed", sa.Integer(), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["run_id"], ["ingestion_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "source_id", name="uq_ingestion_run_source"),
    )
    op.create_index(
        op.f("ix_ingestion_source_runs_run_id"),
        "ingestion_source_runs",
        ["run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ingestion_source_runs_source_id"),
        "ingestion_source_runs",
        ["source_id"],
        unique=False,
    )
    op.create_table(
        "ingestion_decisions",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("source_run_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("external_job_id", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("canonical_url", sa.Text(), nullable=False),
        sa.Column("location", sa.Text(), nullable=True),
        sa.Column("resolved_country", sa.String(length=2), nullable=True),
        sa.Column("decision", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.String(length=50), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["run_id"], ["ingestion_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_run_id"], ["ingestion_source_runs.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_ingestion_decision_filter",
        "ingestion_decisions",
        ["run_id", "decision", "source_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ingestion_decisions_run_id"),
        "ingestion_decisions",
        ["run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ingestion_decisions_source_id"),
        "ingestion_decisions",
        ["source_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ingestion_decisions_source_run_id"),
        "ingestion_decisions",
        ["source_run_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_ingestion_decisions_source_run_id"), table_name="ingestion_decisions"
    )
    op.drop_index(
        op.f("ix_ingestion_decisions_source_id"), table_name="ingestion_decisions"
    )
    op.drop_index(
        op.f("ix_ingestion_decisions_run_id"), table_name="ingestion_decisions"
    )
    op.drop_index("ix_ingestion_decision_filter", table_name="ingestion_decisions")
    op.drop_table("ingestion_decisions")
    op.drop_index(
        op.f("ix_ingestion_source_runs_source_id"), table_name="ingestion_source_runs"
    )
    op.drop_index(
        op.f("ix_ingestion_source_runs_run_id"), table_name="ingestion_source_runs"
    )
    op.drop_table("ingestion_source_runs")
    op.drop_index(
        "uq_ingestion_global_policy",
        table_name="ingestion_policies",
        postgresql_where=sa.text("source_id IS NULL"),
    )
    op.drop_table("ingestion_policies")
    op.drop_index(
        "uq_ingestion_active_run",
        table_name="ingestion_runs",
        postgresql_where=sa.text("status IN ('PENDING','RUNNING')"),
    )
    op.drop_index("ix_ingestion_run_created", table_name="ingestion_runs")
    op.drop_table("ingestion_runs")
    # ### end Alembic commands ###
