"""hybrid_dedup_occurrences

Revision ID: 0011_hybrid_dedup
Revises: 0010_ingestion_control
Create Date: 2026-10-05 14:11:19.662325+00:00

"""

import json
import re
import unicodedata
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0011_hybrid_dedup"
down_revision: str | None = "0010_ingestion_control"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dedup_candidates",
        sa.Column("left_job_id", sa.UUID(), nullable=False),
        sa.Column("right_job_id", sa.UUID(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("outcome", sa.String(length=20), nullable=False),
        sa.Column("signals", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution", sa.String(length=30), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("left_job_id < right_job_id", name="ck_dedup_order"),
        sa.ForeignKeyConstraint(["left_job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["right_job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("left_job_id", "right_job_id", name="uq_dedup_pair"),
    )
    op.create_table(
        "job_merge_records",
        sa.Column("source_job_id", sa.UUID(), nullable=False),
        sa.Column("target_job_id", sa.UUID(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("signals", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["source_job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_job_id"),
    )
    op.create_table(
        "job_occurrences",
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("external_job_id", sa.String(length=255), nullable=True),
        sa.Column("canonical_url", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reference", sa.Text(), nullable=True),
        sa.Column(
            "projection", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("dedup_outcome", sa.String(length=20), nullable=False),
        sa.Column("dedup_score", sa.Integer(), nullable=False),
        sa.Column(
            "dedup_signals", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE','CLOSED')", name="ck_occurrence_status"
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_id", "canonical_url", name="uq_occurrence_source_url"
        ),
        sa.UniqueConstraint(
            "source_id", "external_job_id", name="uq_occurrence_source_external"
        ),
    )
    op.create_index(
        op.f("ix_job_occurrences_job_id"), "job_occurrences", ["job_id"], unique=False
    )
    op.create_index(
        op.f("ix_job_occurrences_source_id"),
        "job_occurrences",
        ["source_id"],
        unique=False,
    )
    op.create_index(
        "ix_occurrence_source_status",
        "job_occurrences",
        ["source_id", "status"],
        unique=False,
    )
    op.add_column(
        "jobs", sa.Column("dedup_company", sa.Text(), server_default="", nullable=False)
    )
    op.add_column(
        "jobs", sa.Column("dedup_title", sa.Text(), server_default="", nullable=False)
    )
    op.add_column("jobs", sa.Column("merged_into_id", sa.UUID(), nullable=True))
    op.create_index(
        op.f("ix_jobs_dedup_company"), "jobs", ["dedup_company"], unique=False
    )
    op.create_index(op.f("ix_jobs_dedup_title"), "jobs", ["dedup_title"], unique=False)
    op.create_foreign_key(
        "fk_jobs_survivor",
        "jobs",
        "jobs",
        ["merged_into_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "match_results",
        sa.Column(
            "invalidated", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    op.add_column("raw_jobs", sa.Column("occurrence_id", sa.UUID(), nullable=True))
    op.create_index(
        op.f("ix_raw_jobs_occurrence_id"), "raw_jobs", ["occurrence_id"], unique=False
    )
    op.create_foreign_key(
        "fk_raw_occurrence",
        "raw_jobs",
        "job_occurrences",
        ["occurrence_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "job_requirements",
        sa.Column(
            "archived", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    op.drop_constraint("uq_jobs_canonical_url", "jobs", type_="unique")
    bind = op.get_bind()
    # Exactly one occurrence per historical Job, no dedup or merges in migration.
    bind.execute(
        sa.text("""INSERT INTO job_occurrences
      (id,job_id,source_id,external_job_id,canonical_url,status,content_hash,
       first_seen_at,last_seen_at,closed_at,created_at,updated_at,projection,
       dedup_outcome,dedup_score,dedup_signals)
      SELECT gen_random_uuid(),id,source_id,external_job_id,canonical_url,
       status,content_hash,
       first_seen_at,last_seen_at,closed_at,created_at,updated_at,
       jsonb_build_object('company',company,'title',title,'description',description,
         'location',location,'work_mode',work_mode,
         'employment_type',employment_type), 'NEW_JOB',0,'{}'::jsonb FROM jobs""")
    )
    bind.execute(
        sa.text("""UPDATE raw_jobs r SET occurrence_id=o.id FROM job_occurrences o
      WHERE r.job_id=o.job_id AND r.source_id=o.source_id""")
    )
    for row in bind.execute(sa.text("SELECT id,company,title FROM jobs")).mappings():

        def normalized(value):
            return " ".join(
                re.findall(r"\w+", unicodedata.normalize("NFKC", value).casefold())
            )

        bind.execute(
            sa.text(
                "UPDATE jobs SET dedup_company=:company,dedup_title=:title WHERE id=:id"
            ),
            {
                "id": row["id"],
                "company": normalized(row["company"]),
                "title": normalized(row["title"]),
            },
        )
    for row in bind.execute(
        sa.text(
            "SELECT DISTINCT ON (occurrence_id) occurrence_id,raw_content "
            "FROM raw_jobs WHERE occurrence_id IS NOT NULL "
            "ORDER BY occurrence_id,fetched_at DESC,id"
        )
    ).mappings():
        try:
            payload = json.loads(row["raw_content"])
        except (ValueError, TypeError):
            continue
        if isinstance(payload, dict):
            reference = next(
                (
                    str(payload[k]).strip()
                    for k in ("requisition_id", "requisitionId", "jobRequisitionId")
                    if isinstance(payload.get(k), (str, int))
                    and not isinstance(payload[k], bool)
                    and str(payload[k]).strip()
                ),
                None,
            )
            if reference:
                bind.execute(
                    sa.text(
                        "UPDATE job_occurrences SET reference=:reference WHERE id=:id"
                    ),
                    {"id": row["occurrence_id"], "reference": reference},
                )


def downgrade() -> None:
    if op.get_bind().scalar(
        sa.text(
            "SELECT EXISTS(SELECT 1 FROM job_merge_records) OR "
            "EXISTS(SELECT 1 FROM job_occurrences GROUP BY job_id HAVING count(*)>1)"
        )
    ):
        raise RuntimeError(
            "A5 contains multi-source/merged data; "
            "downgrade requires an explicit data recovery plan"
        )
    op.create_unique_constraint("uq_jobs_canonical_url", "jobs", ["canonical_url"])
    op.drop_column("job_requirements", "archived")
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint("fk_raw_occurrence", "raw_jobs", type_="foreignkey")
    op.drop_index(op.f("ix_raw_jobs_occurrence_id"), table_name="raw_jobs")
    op.drop_column("raw_jobs", "occurrence_id")
    op.drop_column("match_results", "invalidated")
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint("fk_jobs_survivor", "jobs", type_="foreignkey")
    op.drop_index(op.f("ix_jobs_dedup_title"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_dedup_company"), table_name="jobs")
    op.drop_column("jobs", "merged_into_id")
    op.drop_column("jobs", "dedup_title")
    op.drop_column("jobs", "dedup_company")
    op.drop_index("ix_occurrence_source_status", table_name="job_occurrences")
    op.drop_index(op.f("ix_job_occurrences_source_id"), table_name="job_occurrences")
    op.drop_index(op.f("ix_job_occurrences_job_id"), table_name="job_occurrences")
    op.drop_table("job_occurrences")
    op.drop_table("job_merge_records")
    op.drop_table("dedup_candidates")
    # ### end Alembic commands ###
