"""API dependencies package."""

from backend.interfaces.api.dependencies.crawler import (
    ATSAdapterRegistryDep,
    CrawlerOrchestratorDep,
    CrawlHistoryServiceDep,
    CrawlPersistenceManagerDep,
    SafeHttpClientDep,
    get_adapter_registry,
    get_crawl_history_service,
    get_crawl_persistence_manager,
    get_crawler_orchestrator,
    get_safe_http_client,
)
from backend.interfaces.api.dependencies.database import DbSession, get_db_session
from backend.interfaces.api.dependencies.job_processing import (
    CrawlRunRepositoryDep,
    JobIngestionServiceDep,
    JobLifecycleServiceDep,
    JobNormalizerDep,
    JobQueryServiceDep,
    JobRepositoryDep,
    RawJobRepositoryDep,
    get_crawl_run_repository,
    get_job_ingestion_service,
    get_job_lifecycle_service,
    get_job_normalizer,
    get_job_query_service,
    get_job_repository,
    get_raw_job_repository,
)
from backend.interfaces.api.dependencies.sources import (
    CatalogParserDep,
    SourceHealthProbeDep,
    SourceRegistryDep,
    get_catalog_parser,
    get_source_health_probe,
    get_source_registry_service,
    get_source_repository,
)

__all__ = [
    "ATSAdapterRegistryDep",
    "CatalogParserDep",
    "CrawlHistoryServiceDep",
    "CrawlPersistenceManagerDep",
    "CrawlRunRepositoryDep",
    "CrawlerOrchestratorDep",
    "DbSession",
    "JobIngestionServiceDep",
    "JobLifecycleServiceDep",
    "JobNormalizerDep",
    "JobQueryServiceDep",
    "JobRepositoryDep",
    "RawJobRepositoryDep",
    "SafeHttpClientDep",
    "SourceHealthProbeDep",
    "SourceRegistryDep",
    "get_adapter_registry",
    "get_catalog_parser",
    "get_crawl_history_service",
    "get_crawl_persistence_manager",
    "get_crawl_run_repository",
    "get_crawler_orchestrator",
    "get_db_session",
    "get_job_ingestion_service",
    "get_job_lifecycle_service",
    "get_job_normalizer",
    "get_job_query_service",
    "get_job_repository",
    "get_raw_job_repository",
    "get_safe_http_client",
    "get_source_health_probe",
    "get_source_registry_service",
    "get_source_repository",
]
